package me.personal.testing;

import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.Persistence;
import org.junit.jupiter.api.*;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;

/**
 * =====================================================================
 *  INTEGRATION TEST
 * =====================================================================
 *
 * WHAT:
 *   Tests multiple components WORKING TOGETHER.
 *   Here: Java code + JPA/Hibernate + real H2 database.
 *   The "integration" is between your code and the database.
 *
 * WHY:
 *   - Unit tests can pass but integration can still fail
 *     (e.g., wrong SQL, wrong column names, constraint violations)
 *   - Catches issues at the BOUNDARY between components
 *   - Verifies that your SQL/JPQL actually works against a real DB
 *
 * WHEN TO WRITE:
 *   - For anything that talks to external systems (DB, API, file system)
 *   - For repository/DAO classes
 *   - When you need to verify SQL, transactions, constraints
 *
 * CHARACTERISTICS:
 *   - Slower than unit tests (DB setup/teardown)
 *   - Requires external resources (here: H2 in-memory DB)
 *   - Tests the "wiring" between components
 *   - May need setup/teardown for DB state
 *
 * KEY DIFFERENCE FROM UNIT TEST:
 *   Unit test:        Calculator.add(3, 7) → 10   (pure logic, no I/O)
 *   Integration test: UserRepository.save() → actually writes to DB → read back and verify
 */
@DisplayName("Integration Test — UserRepository + JPA + H2")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class IntegrationTest_UserRepositoryTest {

    // Shared across all tests (expensive to create — like a connection pool)
    private static EntityManagerFactory emf;
    private static UserRepository repository;

    /**
     * @BeforeAll — runs ONCE before all tests.
     * Creates the EntityManagerFactory (which creates the DB schema).
     * This is the "integration" — real Hibernate talking to real H2.
     */
    @BeforeAll
    static void setup() {
        emf = Persistence.createEntityManagerFactory("test-db");
        repository = new UserRepository(emf);
    }

    @AfterAll
    static void teardown() {
        emf.close();
    }

    // =================================================================
    //  CRUD integration tests — verify data actually persists in DB
    // =================================================================

    @Test
    @Order(1)
    @DisplayName("should save a user to the database")
    void save() {
        // Arrange
        SimpleUser user = SimpleUser.builder()
                .name("Alice")
                .email("alice@test.com")
                .age(25)
                .build();

        // Act — this actually executes INSERT SQL against H2
        repository.save(user);

        // Assert — ID is auto-generated by the database
        assertThat(user.getId()).isNotNull();
        assertThat(user.getId()).isGreaterThan(0);
    }

    @Test
    @Order(2)
    @DisplayName("should find user by ID from the database")
    void findById() {
        // Act — this actually executes SELECT SQL against H2
        Optional<SimpleUser> found = repository.findById(1L);

        // Assert
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("Alice");
        assertThat(found.get().getEmail()).isEqualTo("alice@test.com");
    }

    @Test
    @Order(3)
    @DisplayName("should find user by email using JPQL query")
    void findByEmail() {
        Optional<SimpleUser> found = repository.findByEmail("alice@test.com");

        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("Alice");
    }

    @Test
    @Order(4)
    @DisplayName("should return empty when user not found")
    void findByEmail_notFound() {
        Optional<SimpleUser> found = repository.findByEmail("nonexistent@test.com");

        assertThat(found).isEmpty();
    }

    @Test
    @Order(5)
    @DisplayName("should save multiple users and find all")
    void findAll() {
        repository.save(SimpleUser.builder().name("Bob").email("bob@test.com").age(30).build());
        repository.save(SimpleUser.builder().name("Charlie").email("charlie@test.com").age(35).build());

        List<SimpleUser> all = repository.findAll();

        assertThat(all).hasSizeGreaterThanOrEqualTo(3);
        assertThat(all).extracting(SimpleUser::getName).contains("Alice", "Bob", "Charlie");
    }

    @Test
    @Order(6)
    @DisplayName("should update user in the database")
    void update() {
        // Arrange — load existing user
        SimpleUser user = repository.findByEmail("alice@test.com").orElseThrow();
        user.setAge(26);

        // Act — merge back to DB
        repository.update(user);

        // Assert — read from DB again to verify
        SimpleUser reloaded = repository.findById(user.getId()).orElseThrow();
        assertThat(reloaded.getAge()).isEqualTo(26);
    }

    @Test
    @Order(7)
    @DisplayName("should delete user from the database")
    void delete() {
        SimpleUser user = repository.findByEmail("charlie@test.com").orElseThrow();
        Long id = user.getId();

        // Act
        repository.deleteById(id);

        // Assert — user is gone from DB
        Optional<SimpleUser> deleted = repository.findById(id);
        assertThat(deleted).isEmpty();
    }

    // =================================================================
    //  Integration-specific tests — things only caught with a real DB
    // =================================================================

    @Test
    @Order(8)
    @DisplayName("should enforce unique email constraint (DB-level)")
    void uniqueEmailConstraint() {
        // Alice already exists with alice@test.com
        SimpleUser duplicate = SimpleUser.builder()
                .name("Alice Duplicate")
                .email("alice@test.com")  // same email!
                .age(99)
                .build();

        // This would pass in a unit test with mocks, but FAILS with a real DB
        assertThatThrownBy(() -> repository.save(duplicate))
                .isInstanceOf(Exception.class);  // ConstraintViolationException
    }
}
